(function(){
  const SERVER=window.PLANOWANIE_SERVER;
  let token=localStorage.getItem('planowanieAuthToken')||'';
  window.PLANOWANIE_AUTH_TOKEN=token;
  const originalIo=window.io;
  if(typeof originalIo==='function')window.io=function(url,opts){opts=opts||{};opts.auth=Object.assign({},opts.auth||{},{token:window.PLANOWANIE_AUTH_TOKEN||''});return originalIo(url,opts)};
  const css=document.createElement('style');css.textContent='#authGate{position:fixed;inset:0;z-index:9999;display:grid;place-items:center;background:#06131f;padding:18px}#authBox{width:min(460px,94vw);background:#0d2333;border:1px solid #385568;border-radius:16px;padding:26px;box-shadow:0 25px 70px #000c;color:#eef3f5;font-family:Georgia,serif}#authBox h1{margin:0;color:#f3d47f;text-align:center;font-size:38px}#authBox .sub{text-align:center;color:#9daeba;font:13px Arial;margin:6px 0 22px}#authBox input{width:100%;box-sizing:border-box;margin:7px 0;padding:13px;border-radius:9px;border:1px solid #38566c;background:#071420;color:#fff;font-size:15px}#authBox button{width:100%;margin-top:9px;padding:12px;border-radius:8px;border:1px solid #79c9ee;color:#fff;background:#075c88;font:800 13px Arial;cursor:pointer}#authBox button.alt{background:#152737;border-color:#536b7e}#authMsg{min-height:20px;margin-top:12px;text-align:center;font:13px Arial;color:#fca5a5}.authUser{position:fixed;right:18px;top:18px;z-index:100;font:12px Arial;color:#eef3f5}.authUser button{margin-left:8px;padding:6px 10px;border-radius:6px;border:1px solid #536b7e;background:#152737;color:#fff;cursor:pointer}';document.head.appendChild(css);
  function gate(){const g=document.createElement('div');g.id='authGate';g.innerHTML='<div id="authBox"><h1>♠ Planowanie</h1><div class="sub">Zaloguj się, aby grać online</div><input id="authName" maxlength="18" placeholder="Nazwa użytkownika"><input id="authPass" type="password" minlength="6" placeholder="Hasło"><button id="authLogin">Zaloguj się</button><button id="authRegister" class="alt">Utwórz konto</button><div id="authMsg"></div></div>';document.body.appendChild(g);}
  function message(t){const e=document.getElementById('authMsg');if(e)e.textContent=t;}
  async function request(path,body){const r=await fetch(SERVER+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Błąd serwera.');return d;}
  function logged(username){window.PLANOWANIE_AUTH_TOKEN=token;const g=document.getElementById('authGate');if(g)g.remove();const n=document.getElementById('name');if(n){n.value=username;n.readOnly=true}let u=document.getElementById('authUser');if(!u){u=document.createElement('div');u.id='authUser';u.className='authUser';u.innerHTML='<span></span><button>Wyloguj</button>';document.body.appendChild(u);u.querySelector('button').onclick=()=>{localStorage.removeItem('planowanieAuthToken');location.reload()}}u.querySelector('span').textContent='Zalogowany: '+username;}
  async function login(){try{const d=await request('/auth/login',{username:authName.value.trim(),password:authPass.value});token=d.token;localStorage.setItem('planowanieAuthToken',token);logged(d.username)}catch(e){message(e.message)}}
  async function register(){try{const d=await request('/auth/register',{username:authName.value.trim(),password:authPass.value});token=d.token;localStorage.setItem('planowanieAuthToken',token);logged(d.username)}catch(e){message(e.message)}}
  async function boot(){gate();authLogin.onclick=login;authRegister.onclick=register;if(token){try{const r=await fetch(SERVER+'/auth/me',{headers:{Authorization:'Bearer '+token}});if(r.ok){const d=await r.json();logged(d.username)}}catch(e){}}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
