/* Gameplay polish: trump choice, score sheet, equipped decks and extra play protection. */
(function(){
  const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const deckClass=id=>`deckStyle-${id||'classic'}`;
  const suitName={'♣':'Trefl','♦':'Karo','♥':'Kier','♠':'Pik'};
  function addCss(){const s=document.createElement('style');s.textContent=`.trumpChooser{display:flex;gap:9px;justify-content:center;flex-wrap:wrap;margin:12px 0}.trumpChoice{min-width:82px;font-size:20px}.trumpChoice.redSuit{color:#ffb5b5}.scoreWrap{overflow-x:auto}.scoreSheet{min-width:760px}.scoreSheet th{background:#e8dcc1}.scoreSheet td.roundCell{font-weight:800}.scoreSheet .ok{color:#14753b}.scoreSheet .miss{text-decoration:line-through;color:#a42b2b}.scoreSheet .pending{color:#705f45}.deckNotice{font-size:11px;color:#91a5b4;margin:0 10px}.phase{font-family:Arial,sans-serif}`;document.head.appendChild(s)}
  function applyDecks(state){const room=state?.room;if(!room)return;const me=room.players.find(p=>String(p.id)===String(state.myId));document.querySelectorAll('#hand .playing').forEach(el=>{['classic','red','blue','gold','neon','royal'].forEach(x=>el.classList.remove('deckStyle-'+x));el.classList.add(deckClass(me?.equippedDeck));});const slots=document.querySelectorAll('#trick .slot');(room.trick||[]).forEach((t,i)=>{const p=room.players.find(x=>x.id===t.player),el=slots[i];if(el)el.classList.add(deckClass(p?.equippedDeck));})}
  function scoreCell(r){if(!r)return '';return r.exact?`<span class="ok">${r.decl} ✓ +${r.points}</span>`:`<span class="miss">${r.decl}</span> <span>✕ 0</span>`}
  function renderSheet(state){const room=state?.room;if(!room)return;const body=document.getElementById('sheet');if(!body)return;const table=body.closest('table');if(!table)return;const rounds=room.roundHistory||[];table.classList.add('scoreSheet');table.querySelector('thead').innerHTML='<tr><th>Gracz</th>'+Array.from({length:room.maxRounds||0},(_,i)=>`<th>R${i+1}</th>`).join('')+'<th>Suma</th></tr>';body.innerHTML=room.players.map(p=>{const cells=Array.from({length:room.maxRounds||0},(_,i)=>{const rr=rounds.find(x=>x.round===i+1),r=rr?.results?.find(x=>String(x.playerId)===String(p.id));if(r)return `<td class="roundCell">${scoreCell(r)}</td>`;if(i+1===room.round&&p.decl!==null)return `<td class="roundCell pending">${p.decl}</td>`;return '<td class="roundCell">—</td>'});return `<tr><td><b>${esc(p.name)}</b></td>${cells.join('')}<td class="total">${p.score}</td></tr>`}).join('')}
  function renderTrump(state){const room=state?.room;if(!room||room.phase!=='trump')return;const area=document.getElementById('declArea');if(!area)return;if(String(room.currentTrumpChooser)===String(state.myId)){area.innerHTML='<div class="phase"><h2>Wybierz atut</h2><p>To Twoja tura. Wybierz kolor, który będzie atutem.</p><div class="trumpChooser">'+['♣','♦','♥','♠'].map(s=>`<button type="button" class="btn trumpChoice ${s==='♥'||s==='♦'?'redSuit':''}" data-suit="${s}">${s}</button>`).join('')+'</div></div>';area.querySelectorAll('.trumpChoice').forEach(b=>b.onclick=()=>{area.querySelectorAll('.trumpChoice').forEach(x=>x.disabled=true);if(window.planowanieSocket)window.planowanieSocket.emit('chooseTrump',b.dataset.suit)})}else{const p=room.players.find(x=>String(x.id)===String(room.currentTrumpChooser));area.innerHTML=`<div class="phase"><h2>Czekaj na wybór atutu</h2><p>Gracz <b>${esc(p?.name||'')}</b> wybiera atut.</p></div>`}}
  function patch(){const socket=window.planowanieSocket;if(!socket)return false;if(socket.__planowanieEnhancements)return true;socket.__planowanieEnhancements=true;socket.on('state',state=>setTimeout(()=>{window.__planowanieLastState=state;renderTrump(state);renderSheet(state);applyDecks(state);const h=document.querySelector('.handHeader');if(h&&!h.querySelector('.deckNotice')){const n=document.createElement('span');n.className='deckNotice';h.insertBefore(n,h.querySelector('.sortbar'))}const me=state.room.players.find(p=>String(p.id)===String(state.myId)),n=h?.querySelector('.deckNotice');if(n)n.textContent='Talia: '+(me?.equippedDeck||'classic')},0));return true}
  function boot(){addCss();const timer=setInterval(()=>{if(patch())clearInterval(timer)},100)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
