/* Social + shop layer for Planowanie Online */
(function(){
const S=window.PLANOWANIE_SERVER||'https://planowanie-server.onrender.com';
const token=()=>localStorage.getItem('planowanieAuthToken')||'';
const api=async(p,o={})=>{const h={'Content-Type':'application/json',...(o.headers||{})};if(token())h.Authorization='Bearer '+token();const r=await fetch(S+p,{...o,headers:h});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'Błąd serwera.');return d};
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
let modal;
function style(){const s=document.createElement('style');s.textContent='.socialModal{position:fixed;inset:0;z-index:7000;display:flex;align-items:center;justify-content:center;padding:18px;background:#020711cc;backdrop-filter:blur(8px)}.socialModal.hidden{display:none!important}.socialCard{width:min(760px,95vw);max-height:88vh;overflow:auto;background:linear-gradient(145deg,#102333,#06111c);border:1px solid #506b7b;border-radius:18px;padding:24px;box-shadow:0 25px 90px #000e;color:#eef3f5;font-family:Arial}.socialCard h2{margin:0 0 4px;color:#f1d994;font:700 29px Georgia}.socialSearch{display:flex;gap:8px;margin:12px 0}.socialSearch input{flex:1;padding:12px;border-radius:10px;border:1px solid #304a5b;background:#081521;color:#fff}.socialItem{display:flex;align-items:center;gap:12px;padding:11px;margin:8px 0;border:1px solid #304a5b;border-radius:12px;background:#091925}.socialAvatar{width:40px;height:40px;border-radius:50%;display:grid;place-items:center;background:#0a1322;border:1px solid #40576a;font-size:23px}.socialGrow{flex:1}.socialMuted{color:#93a6b4;font-size:13px}.socialCoin{color:#f6d56e;font-weight:700}.deckGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px}.deckItem{border:1px solid #304a5b;background:#091925;border-radius:14px;padding:14px}.deckVisual{height:110px;border-radius:10px;display:grid;place-items:center;font-size:48px;margin-bottom:10px;border:2px solid #667b88}.deckVisual.classic{background:linear-gradient(135deg,#12365a,#071421)}.deckVisual.red{background:linear-gradient(135deg,#7a1f25,#24080b)}.deckVisual.blue{background:linear-gradient(135deg,#1b4f8a,#07142d)}.deckVisual.gold{background:linear-gradient(135deg,#8a6a1d,#2c2107)}.deckVisual.neon{background:linear-gradient(135deg,#0d5b63,#16203f)}.deckVisual.royal{background:linear-gradient(135deg,#2a2a2e,#050506)}.deckOwned{color:#86efac;font-size:12px}.deckPrice{color:#f6d56e;font-weight:700;margin:7px 0}.socialError{padding:10px;border-radius:10px;margin:10px 0;background:#481d22;color:#fecaca}.socialClose{float:right}.standing .handPanel{visibility:hidden;pointer-events:none}';document.head.appendChild(s)}
function ensure(){if(modal)return;modal=document.createElement('div');modal.className='socialModal hidden';modal.innerHTML='<div class="socialCard"><button class="btn dark socialClose" id="socialClose">Wróć</button><h2 id="socialTitle"></h2><div id="socialBody"></div></div>';document.body.appendChild(modal);document.getElementById('socialClose').onclick=close;modal.onclick=e=>{if(e.target===modal)close()}}
function open(t,h){ensure();document.getElementById('socialTitle').textContent=t;document.getElementById('socialBody').innerHTML=h;modal.classList.remove('hidden')}
function close(){if(modal)modal.classList.add('hidden')}
async function friends(){if(!token())return open('Znajomi','<div class="socialError">Musisz być zalogowany.</div>');open('Znajomi','<div>Wyszukaj gracza po loginie.</div><div class="socialSearch"><input id="friendQ" placeholder="Login gracza"><button class="btn" id="friendSearch">Szukaj</button></div><div id="friendResults"></div><h3>Twoi znajomi</h3><div id="friendList">Ładowanie…</div>');document.getElementById('friendSearch').onclick=search;loadFriends()}
async function search(){const q=document.getElementById('friendQ').value.trim(),box=document.getElementById('friendResults');if(q.length<2)return box.innerHTML='<div class="socialError">Wpisz co najmniej 2 znaki.</div>';box.textContent='Szukam…';try{const d=await api('/api/friends/search?q='+encodeURIComponent(q));box.innerHTML=d.players.length?d.players.map(p=>`<div class="socialItem"><span class="socialAvatar">${esc(p.avatar)}</span><div class="socialGrow"><b>${esc(p.username)}</b></div>${p.isFriend?'<span>✓ Znajomy</span>':`<button class="btn addFriend" data-id="${p.id}">Dodaj</button>`}</div>`).join(''):'<div>Nie znaleziono gracza.</div>';box.querySelectorAll('.addFriend').forEach(b=>b.onclick=()=>add(b.dataset.id,b))}catch(e){box.innerHTML='<div class="socialError">'+esc(e.message)+'</div>'}}
async function loadFriends(){const box=document.getElementById('friendList');if(!box)return;try{const d=await api('/api/friends');box.innerHTML=d.friends.length?d.friends.map(p=>`<div class="socialItem"><span class="socialAvatar">${esc(p.avatar)}</span><div class="socialGrow"><b>${esc(p.username)}</b></div><span>✓</span></div>`).join(''):'<div>Nie masz jeszcze znajomych.</div>'}catch(e){box.innerHTML='<div class="socialError">'+esc(e.message)+'</div>'}}
async function add(id,b){try{await api('/api/friends/add',{method:'POST',body:JSON.stringify({userId:Number(id)})});b.outerHTML='<span>✓ Znajomy</span>'}catch(e){alert(e.message)}}
function statePlayers(){return window.__planowanieLastState?.room?.players||[]}
function inGameFriends(){if(!token())return open('Znajomi przy stole','<div class="socialError">Zaloguj się, aby dodawać graczy.</div>');const ps=statePlayers().filter(p=>p.accountId&&p.accountUsername&&String(p.accountId)!==String(window.__planowanieMyAccountId));if(!ps.length)return open('Znajomi przy stole','<div>Brak innego zalogowanego gracza przy stole.</div>');open('Znajomi przy stole',ps.map(p=>`<div class="socialItem"><span class="socialAvatar">${esc(p.avatar)}</span><div class="socialGrow"><b>${esc(p.accountUsername)}</b><div class="socialMuted">Gra z Tobą</div></div><button class="btn seatAdd" data-id="${p.accountId}">Dodaj</button></div>`).join(''));modal.querySelectorAll('.seatAdd').forEach(b=>b.onclick=()=>add(b.dataset.id,b))}
async function shop(){if(!token())return open('Sklep','<div class="socialError">Zaloguj się, aby kupować talie za coinsy.</div>');open('Sklep','Ładowanie…');try{const d=await api('/api/shop');renderShop(d)}catch(e){open('Sklep','<div class="socialError">'+esc(e.message)+'</div>')}}
function renderShop(d){open('Sklep',`<div style="margin-bottom:14px">🪙 <b>${d.coins}</b> coins</div><div class="deckGrid">${d.decks.map(x=>{const owned=d.ownedDecks.includes(x.id),eq=d.equippedDeck===x.id;return `<div class="deckItem"><div class="deckVisual ${x.id}">${x.emoji}</div><b>${esc(x.name)}</b><div class="deckPrice">${x.price?('🪙 '+x.price):'Darmowa'}</div>${eq?'<span class="deckOwned">✓ Wyposażona</span>':owned?`<button class="btn equip" data-id="${x.id}">Wyposaż</button>`:`<button class="btn buy" data-id="${x.id}">Kup</button>`}</div>`}).join('')}</div>`);modal.querySelectorAll('.buy').forEach(b=>b.onclick=()=>buy(b.dataset.id));modal.querySelectorAll('.equip').forEach(b=>b.onclick=()=>equip(b.dataset.id))}
async function buy(id){try{await api('/api/shop/buy',{method:'POST',body:JSON.stringify({deckId:id})});shop()}catch(e){alert(e.message)}}
async function equip(id){try{await api('/api/shop/equip',{method:'POST',body:JSON.stringify({deckId:id})});shop()}catch(e){alert(e.message)}}
function wire(){style();const nav=document.querySelectorAll('.topbar .navitem');if(nav[1])nav[1].onclick=e=>{e.preventDefault();shop()};if(nav[3])nav[3].onclick=e=>{e.preventDefault();friends()};const timer=setInterval(()=>{const s=window.planowanieSocket;if(!s)return;clearInterval(timer);s.on('state',st=>{window.__planowanieLastState=st;const me=st.room.players.find(p=>String(p.id)===String(st.myId));window.__planowanieMyAccountId=me?.accountId||null;});},200);setTimeout(()=>{const side=document.querySelector('.sideButtons');if(side&&!document.getElementById('gameFriendsBtn')){const b=document.createElement('button');b.id='gameFriendsBtn';b.className='btn';b.type='button';b.textContent='👥 Znajomi';b.onclick=inGameFriends;side.appendChild(b)}},800)}
window.PlanowanieSocial={friends,shop,inGameFriends,api};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();
