/* v11 UI: settings, music tracks, card art, friends-at-table removal */
(function(){
const st=document.createElement('style');st.textContent=`#gameFriendsBtn{display:none!important}.v11Close{position:absolute;right:16px;top:14px;width:38px;height:38px;border-radius:50%;border:1px solid #6b7f8c;background:#111d27;color:#fff;font-size:24px;cursor:pointer}.v10Create>.v10Card{position:relative}.v11TrackRow{display:flex;gap:8px;align-items:center;margin:12px 0}.v11TrackRow select{flex:1;padding:11px;border-radius:10px;border:1px solid #466071;background:#081722;color:#fff}.playing.face-art{overflow:hidden;background-size:100% 100%!important;background-position:center!important;color:transparent!important}.playing.face-J{background-image:url('assets/cards/J.svg')!important}.playing.face-Q{background-image:url('assets/cards/Q.svg')!important}.playing.face-K{background-image:url('assets/cards/K.svg')!important}.playing.face-A{background-image:url('assets/cards/A.svg')!important}.v10Messenger .v10Bubble{color:#fff!important;display:block!important}.v10Messenger .v10Meta{color:#b5c4cf!important}.v10Messenger .v10ChatHistory{display:flex!important;flex-direction:column!important;align-items:stretch!important}.v10Messenger .v10Bubble.mine{align-self:flex-end!important;margin:4px 0!important}.v10Messenger .v10Bubble:not(.mine){align-self:flex-start!important;margin:4px 0!important}.v10Ad{display:none!important}`;document.head.appendChild(st);
let ctx=null,timer=null,track=Number(localStorage.getItem('plTrack')||0),on=localStorage.getItem('plMusicV11')!=='0';const tracks=[[196,247,294,370,330,247,220,277],[220,262,330,392,349,294,262,330],[147,175,220,294,262,220,175,196]];
function audio(){if(!ctx)ctx=new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();return ctx}function stop(){if(timer){clearInterval(timer);timer=null}}function start(){stop();if(!on)return;try{const c=audio(),n=tracks[track];let i=0;timer=setInterval(()=>{const o=c.createOscillator(),g=c.createGain();o.type='triangle';o.frequency.value=n[i++%n.length];g.gain.setValueAtTime(.001,c.currentTime);g.gain.linearRampToValueAtTime(.055,c.currentTime+.04);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.5);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.53)},620)}catch(e){}}function tone(f=600,d=.1){try{const c=audio(),o=c.createOscillator(),g=c.createGain();o.type='triangle';o.frequency.value=f;g.gain.setValueAtTime(.001,c.currentTime);g.gain.exponentialRampToValueAtTime(.14,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+d+.02)}catch(e){}}
function settings(){document.querySelectorAll('.v10Create:not(.hidden)').forEach(m=>{if(!/Ustawienia/i.test(m.textContent||'')||m.querySelector('.v11Close'))return;const card=m.querySelector('.v10Card');if(!card)return;const x=document.createElement('button');x.className='v11Close';x.textContent='×';x.onclick=()=>m.classList.add('hidden');card.appendChild(x);const row=document.createElement('div');row.className='v11TrackRow';row.innerHTML='<label>Piosenka</label><select id="v11Track"><option value="0">Nocny stół</option><option value="1">Karciana przygoda</option><option value="2">Królewski pojedynek</option></select><button class="btn" id="v11TrackPlay">▶</button>';card.appendChild(row);const sel=row.querySelector('#v11Track');sel.value=String(track);row.querySelector('#v11TrackPlay').onclick=()=>{track=Number(sel.value);localStorage.setItem('plTrack',String(track));on=true;localStorage.setItem('plMusicV11','1');start();tone(880,.1)}})}
function art(){document.querySelectorAll('.hand .playing').forEach(c=>{const t=(c.textContent||'').trim();c.classList.remove('face-art','face-J','face-Q','face-K','face-A');for(const r of ['J','Q','K','A'])if(t===r||t.startsWith(r+' ')||t.includes(r+'♥')||t.includes(r+'♦')||t.includes(r+'♣')||t.includes(r+'♠')){c.classList.add('face-art','face-'+r);break}})}
function theme(){const s=window.__planowanieLastState;if(!s)return;const p=(s.room?.players||[]).find(x=>String(x.id)===String(s.myId)),d=p?.equippedDeck||'classic';document.querySelectorAll('.hand .playing').forEach(c=>{['classic','red','blue','gold','neon','royal'].forEach(x=>c.classList.remove('deckStyle-'+x));c.classList.add('deckStyle-'+d);c.classList.toggle('red',/[♥♦]/.test(c.textContent||''))});art()}
function run(){settings();theme();document.getElementById('gameFriendsBtn')?.remove();document.addEventListener('pointerdown',()=>{if(on)start()},{once:true});const s=window.planowanieSocket;if(s&&!s.__v11theme){s.__v11theme=1;s.on('state',()=>setTimeout(theme,40))}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{run();setInterval(()=>{settings();theme();document.getElementById('gameFriendsBtn')?.remove()},700)});else{run();setInterval(()=>{settings();theme();document.getElementById('gameFriendsBtn')?.remove()},700)}
window.PlanowanieV11={start,stop,setTrack:n=>{track=Math.max(0,Math.min(2,Number(n)||0));localStorage.setItem('plTrack',String(track));start()}};
})();