/* v12 UI: player profiles, notifications, early-end vote, leaderboard, stable card sorting */
(function(){
const css=document.createElement('style');css.textContent='.v12Overlay{position:fixed;inset:0;z-index:9000;display:flex;align-items:center;justify-content:center;background:#020711cc}.v12Card{width:min(620px,94vw);max-height:88vh;overflow:auto;background:#0b1c29;border:1px solid #526d7d;border-radius:18px;padding:22px;color:#fff;box-shadow:0 25px 90px #000}.v12Close{float:right;border:1px solid #657d8b;background:#132333;color:#fff;border-radius:50%;width:36px;height:36px;font-size:22px}.v12Stat{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:14px 0}.v12Stat div{padding:12px;border:1px solid #304a5b;border-radius:10px;background:#091925}.v12Toast{position:fixed;z-index:12000;right:24px;bottom:24px;padding:14px 17px;border:1px solid #c59a36;border-radius:12px;background:#101b25;color:#fff;font:700 14px Arial}.v12ChatMsg{padding:3px 0;color:#fff}.v12ChatMsg.mine{text-align:right}.v12ChatText{display:inline-block;background:#163349;border-radius:12px;padding:8px 11px}.v12ChatMsg.mine .v12ChatText{background:#0b5a78}.v12Unread{display:inline-block;width:9px;height:9px;background:#e33;border-radius:50%;margin-left:5px}.chatLine{background:transparent!important;border:0!important;box-shadow:none!important;padding:3px 0!important;margin:2px 0!important;color:#fff!important}.chatLine .chatMeta{display:none!important}.chatLine.mine{text-align:right!important}.chatLine:not(.mine){text-align:left!important}';document.head.appendChild(css);
const esc=x=>String(x??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function toast(t){const x=document.createElement('div');x.className='v12Toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),4500)}
function room(){return window.__planowanieLastState?.room}function me(){return window.__planowanieLastState?.myId}
function modal(title,body){const o=document.createElement('div');o.className='v12Overlay';o.innerHTML='<div class="v12Card"><button class="v12Close">×</button><h2>'+title+'</h2>'+body+'</div>';document.body.appendChild(o);o.querySelector('.v12Close').onclick=()=>o.remove();return o}
function profile(p){if(!p)return;const body='<div style="text-align:center;font-size:64px">'+esc(p.avatar||'😀')+'</div><h3 style="text-align:center">'+esc(p.name||p.accountUsername||'Gracz')+'</h3><div class="v12Stat"><div>Punkty<br><b>'+(p.score||0)+'</b></div><div>Wygrane lewy<br><b>'+(p.won||0)+'</b></div><div>Deklaracja<br><b>'+(p.decl??'—')+'</b></div><div>Lewy w rundzie<br><b>'+(p.won||0)+'</b></div></div>'+(p.accountId&&String(p.accountId)!==String(window.__planowanieMyAccountId)?'<button class="btn v12Add">＋ Dodaj do znajomych</button>':'');const o=modal('Profil gracza',body),b=o.querySelector('.v12Add');if(b)b.onclick=async()=>{try{const t=localStorage.getItem('planowanieAuthToken')||'';const r=await fetch((window.PLANOWANIE_SERVER||'https://planowanie-server.onrender.com')+'/api/friends/add',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+t},body:JSON.stringify({userId:Number(p.accountId)})});const d=await r.json();if(!r.ok)throw Error(d.error||'Błąd');b.textContent='✓ Dodano';b.disabled=true;toast('Dodano do znajomych')}catch(e){toast(e.message)}}}
function seats(){document.querySelectorAll('.seat').forEach((el,i)=>{if(el.__v12)return;el.__v12=1;el.style.cursor='pointer';el.onclick=()=>{const p=room()?.players?.[i];if(p&&String(p.id)!==String(me()))profile(p)}})}
function notices(s){const ps=s?.room?.players||[],old=window.__v12Players||[];ps.forEach(p=>{const q=old.find(x=>x.id===p.id);if(q&&q.connected&&!p.connected)toast(p.name+' zniknął od stołu.');if(!q&&p.id!==me())toast(p.name+' dołączył do stołu.')});if(old.length&&ps.length<old.length)toast('Gracz opuścił stół.');window.__v12Players=ps.map(p=>({...p}));if(s?.room?.phase==='finished'&&!window.__v12Finished){window.__v12Finished=1;const p=ps.find(x=>x.id===me());toast('Gra zakończona • '+(p?.score||0)+' pkt')}}
function endButton(){const r=room();if(!r||r.phase==='lobby'||r.phase==='finished'||document.getElementById('v12End')||r.players[0]?.id!==me())return;const a=document.querySelector('.sideButtons');if(!a)return;const b=document.createElement('button');b.id='v12End';b.className='btn dark';b.textContent='⏹ Zakończ grę';b.onclick=()=>{if(confirm('Poprosić wszystkich o zgodę na zakończenie gry?'))window.planowanieSocket?.emit('requestEndGame')};a.appendChild(b)}
function leader(){const t=localStorage.getItem('planowanieAuthToken')||'',S=window.PLANOWANIE_SERVER||'https://planowanie-server.onrender.com';fetch(S+'/api/leaderboard',{headers:{Authorization:'Bearer '+t}}).then(r=>r.json()).then(d=>{const rows=(d.rows||[]).map((x,i)=>'<div style="padding:11px;border-bottom:1px solid #304a5b"><b>#'+(i+1)+' '+esc(x.username)+'</b><br><small>'+x.coins+' coins • '+x.wins+' wygranych • '+x.losses+' przegranych • '+x.minutes+' min</small></div>').join('');modal('🏆 Topka',rows||'Brak danych')}).catch(()=>toast('Nie udało się pobrać topki.'))}
function leaderButton(){if(document.getElementById('v12Leader'))return;const n=[...document.querySelectorAll('.navitem')].find(x=>/News/i.test(x.textContent));if(!n)return;const b=document.createElement('div');b.id='v12Leader';b.className='navitem';b.innerHTML='<span class="navicon">🏆</span>Topka';b.onclick=leader;n.parentNode.appendChild(b)}
async function account(){try{const t=localStorage.getItem('planowanieAuthToken')||'';if(!t)return;const r=await fetch((window.PLANOWANIE_SERVER||'https://planowanie-server.onrender.com')+'/api/me',{headers:{Authorization:'Bearer '+t}});const d=await r.json();if(d.user)window.__planowanieMyAccountId=d.user.id}catch{}}
function run(){const s=window.planowanieSocket;if(s&&!s.__v12){s.__v12=1;s.on('state',st=>{window.__planowanieLastState=st;notices(st);seats();endButton()});s.on('gameNotice',toast);s.on('rewardNotice',toast)}seats();leaderButton();account()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();setInterval(run,1200);window.PlanowanieV12={profile,toast,leader};})();