const express=require('express');
const http=require('http');
const {Server}=require('socket.io');
const crypto=require('crypto');
const bcrypt=require('bcryptjs');
const {Pool}=require('pg');
const app=express();
const server=http.createServer(app);
app.use(express.json({limit:'700kb'}));
app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,POST,DELETE,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');if(req.method==='OPTIONS')return res.sendStatus(204);next()});
const io=new Server(server,{cors:{origin:'*',methods:['GET','POST']}});
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});
const AVATARS=['😀','😎','🤠','🥶','😈','👑','🦊','🐺','🐼','🐸','🤖','👽','🎩','🃏','♠️','🔥'];
const DECKS={classic:{name:'Klasyczna',price:0,emoji:'C'},red:{name:'Czerwony ogień',price:250,emoji:'R'},blue:{name:'Nocny błękit',price:500,emoji:'B'},gold:{name:'Królewska złota',price:900,emoji:'G'},neon:{name:'Neon',price:1400,emoji:'N'},royal:{name:'Royal Black',price:2200,emoji:'R'}};
const PUBLIC_DECKS=Object.entries(DECKS).map(([id,x])=>({id,...x}));
const SUITS=['♣','♦','♥','♠'],RANKS=['2','3','4','5','6','7','8','9','10','J','Q','K','A'];
const rooms=new Map(),accountSockets=new Map();
const cleanUsername=v=>String(v||'').trim().replace(/\s+/g,'').slice(0,18),validUsername=v=>/^[a-zA-Z0-9_ąćęłńóśźżĄĆĘŁŃÓŚŹŻ-]{3,18}$/.test(v),cleanPassword=v=>String(v||''),cleanAvatar=v=>AVATARS.includes(String(v))?String(v):'😀',cleanName=v=>String(v||'Gracz').trim().slice(0,18)||'Gracz',cleanToken=v=>String(v||'').trim().slice(0,300),makeToken=()=>crypto.randomBytes(48).toString('hex');
function tokenFromReq(req){const a=req.headers.authorization||'';return a.startsWith('Bearer ')?a.slice(7).trim():''}
async function getUserFromToken(token){if(!process.env.DATABASE_URL||!token)return null;const r=await pool.query(`SELECT u.id,u.username,u.avatar,u.coins,u.owned_decks,u.equipped_deck FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=$1 AND s.expires_at>NOW()`,[String(token)]);return r.rows[0]||null}
function publicUser(u){return u?{id:u.id,username:u.username,avatar:u.avatar||'😀',coins:Number(u.coins||0),ownedDecks:Array.isArray(u.owned_decks)?u.owned_decks:['classic'],equippedDeck:u.equipped_deck||'classic'}:null}
async function authUser(req){return getUserFromToken(tokenFromReq(req))}
async function createSession(id){const t=makeToken();await pool.query(`INSERT INTO sessions(token,user_id,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 days')`,[t,id]);return t}
async function initDatabase(){if(!process.env.DATABASE_URL){console.log('WARNING: DATABASE_URL nie jest ustawione.');return}await pool.query(`
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,username VARCHAR(18) UNIQUE NOT NULL,password_hash TEXT NOT NULL,avatar VARCHAR(20) NOT NULL DEFAULT '😀',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE users ADD COLUMN IF NOT EXISTS coins INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE users ADD COLUMN IF NOT EXISTS owned_decks JSONB NOT NULL DEFAULT '["classic"]'::jsonb;
ALTER TABLE users ADD COLUMN IF NOT EXISTS equipped_deck VARCHAR(32) NOT NULL DEFAULT 'classic';
CREATE TABLE IF NOT EXISTS sessions(id SERIAL PRIMARY KEY,token TEXT UNIQUE NOT NULL,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at TIMESTAMP NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS profile_photos(user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,photo TEXT NOT NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS friends(user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,friend_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_id,friend_id));
CREATE TABLE IF NOT EXISTS messages(id BIGSERIAL PRIMARY KEY,from_user INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,to_user INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,body TEXT NOT NULL,kind VARCHAR(20) NOT NULL DEFAULT 'chat',room_code VARCHAR(12),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,read_at TIMESTAMP NULL);
CREATE INDEX IF NOT EXISTS users_username_idx ON users(LOWER(username));CREATE INDEX IF NOT EXISTS messages_pair_idx ON messages(from_user,to_user,created_at);
`);console.log('Database ready.')}
app.post('/api/register',async(req,res)=>{try{const username=cleanUsername(req.body?.username),password=cleanPassword(req.body?.password),avatar=cleanAvatar(req.body?.avatar);if(!validUsername(username))return res.status(400).json({error:'Login musi mieć 3–18 znaków.'});if(password.length<6||password.length>100)return res.status(400).json({error:'Hasło musi mieć 6–100 znaków.'});const ex=await pool.query('SELECT id FROM users WHERE LOWER(username)=LOWER($1)',[username]);if(ex.rows.length)return res.status(409).json({error:'Taki login jest już zajęty.'});const hash=await bcrypt.hash(password,12),r=await pool.query(`INSERT INTO users(username,password_hash,avatar) VALUES($1,$2,$3) RETURNING id,username,avatar,coins,owned_decks,equipped_deck`,[username,hash,avatar]);res.json({ok:true,user:publicUser(r.rows[0]),token:await createSession(r.rows[0].id)})}catch(e){console.error(e);res.status(500).json({error:'Nie udało się utworzyć konta.'})}});
app.post('/api/login',async(req,res)=>{try{const username=cleanUsername(req.body?.username),password=cleanPassword(req.body?.password),r=await pool.query(`SELECT id,username,password_hash,avatar,coins,owned_decks,equipped_deck FROM users WHERE LOWER(username)=LOWER($1)`,[username]),u=r.rows[0];if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'Nieprawidłowy login lub hasło.'});res.json({ok:true,user:publicUser(u),token:await createSession(u.id)})}catch(e){res.status(500).json({error:'Nie udało się zalogować.'})}});
app.get('/api/me',async(req,res)=>{try{const u=await authUser(req);if(!u)return res.status(401).json({error:'Sesja wygasła.'});res.json({ok:true,user:publicUser(u)})}catch(e){res.status(500).json({error:'Błąd serwera.'})}});
app.post('/api/profile',async(req,res)=>{try{const u=await authUser(req);if(!u)return res.status(401).json({error:'Sesja wygasła.'});const r=await pool.query(`UPDATE users SET avatar=$1 WHERE id=$2 RETURNING id,username,avatar,coins,owned_decks,equipped_deck`,[cleanAvatar(req.body?.avatar),u.id]);res.json({ok:true,user:publicUser(r.rows[0])})}catch(e){res.status(500).json({error:'Nie udało się zapisać profilu.'})}});
app.post('/api/logout',async(req,res)=>{try{const t=tokenFromReq(req);if(t)await pool.query('DELETE FROM sessions WHERE token=$1',[t]);res.json({ok:true})}catch(e){res.json({ok:true})}});
app.post('/api/profile-photo',async(req,res)=>{try{const u=await authUser(req),photo=String(req.body?.photo||'');if(!u)return res.status(401).json({error:'Sesja wygasła.'});if(!photo.startsWith('data:image/'))return res.status(400).json({error:'Nieprawidłowe zdjęcie.'});if(photo.length>650000)return res.status(413).json({error:'Zdjęcie jest za duże.'});await pool.query(`INSERT INTO profile_photos(user_id,photo) VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET photo=EXCLUDED.photo,updated_at=NOW()`,[u.id,photo]);res.json({ok:true,photo})}catch(e){console.error(e);res.status(500).json({error:'Nie udało się zapisać zdjęcia.'})}});
app.get('/api/profile-photo',async(req,res)=>{try{const u=await authUser(req);if(!u)return res.status(401).json({error:'Sesja wygasła.'});const r=await pool.query('SELECT photo FROM profile_photos WHERE user_id=$1',[u.id]);res.json({ok:true,photo:r.rows[0]?.photo||null})}catch(e){res.status(500).json({error:'Błąd profilu.'})}});
app.delete('/api/profile-photo',async(req,res)=>{try{const u=await authUser(req);if(!u)return res.status(401).json({error:'Sesja wygasła.'});await pool.query('DELETE FROM profile_photos WHERE user_id=$1',[u.id]);res.json({ok:true})}catch(e){res.status(500).json({error:'Błąd profilu.'})}});
app.post('/api/reward/ad',async(req,res)=>{try{const u=await authUser(req);if(!u)return res.status(401).json({error:'Sesja wygasła.'});const r=await pool.query(`UPDATE users SET coins=coins+1000 WHERE id=$1 RETURNING id,username,avatar,coins,owned_decks,equipped_deck`,[u.id]);res.json({ok:true,reward:1000,user:publicUser(r.rows[0])})}catch(e){res.status(500).json({error:'Błąd nagrody.'})}});
app.get('/api/friends',async(req,res)=>{try{const u=await authUser(req);if(!u)return res.status(401).json({error:'Zaloguj się.'});const r=await pool.query(`SELECT u.id,u.username,u.avatar FROM friends f JOIN users u ON u.id=f.friend_id WHERE f.user_id=$1 ORDER BY LOWER(u.username)`,[u.id]);res.json({ok:true,friends:r.rows})}catch(e){res.status(500).json({error:'Nie udało się pobrać znajomych.'})}});
app.get('/api/friends/search',async(req,res)=>{try{const u=await authUser(req);if(!u)return res.status(401).json({error:'Zaloguj się.'});const q=cleanUsername(req.query?.q||'');if(q.length<2)return res.json({ok:true,players:[]});const r=await pool.query(`SELECT id,username,avatar FROM users WHERE id<>$1 AND LOWER(username) LIKE LOWER($2) ORDER BY LOWER(username) LIMIT 20`,[u.id,`%${q}%`]),f=await pool.query('SELECT friend_id FROM friends WHERE user_id=$1',[u.id]),set=new Set(f.rows.map(x=>Number(x.friend_id)));res.json({ok:true,players:r.rows.map(x=>({...x,isFriend:set.has(Number(x.id))}))})}catch(e){res.status(500).json({error:'Nie udało się wyszukać graczy.'})}});
app.post('/api/friends/add',async(req,res)=>{try{const u=await authUser(req),id=Number(req.body?.userId);if(!u)return res.status(401).json({error:'Zaloguj się.'});if(!Number.isInteger(id)||id===Number(u.id))return res.status(400).json({error:'Nieprawidłowy gracz.'});const t=await pool.query('SELECT id,username,avatar FROM users WHERE id=$1',[id]);if(!t.rows[0])return res.status(404).json({error:'Nie znaleziono gracza.'});await pool.query('INSERT INTO friends(user_id,friend_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[u.id,id]);await pool.query('INSERT INTO friends(user_id,friend_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[id,u.id]);res.json({ok:true,friend:t.rows[0]})}catch(e){res.status(500).json({error:'Nie udało się dodać znajomego.'})}});
app.get('/api/messages',async(req,res)=>{try{const u=await authUser(req);if(!u)return res.status(401).json({error:'Zaloguj się.'});const r=await pool.query(`SELECT m.id,m.from_user,m.to_user,m.body,m.kind,m.room_code,m.created_at,f.username AS from_username,t.username AS to_username,f.avatar AS from_avatar FROM messages m JOIN users f ON f.id=m.from_user JOIN users t ON t.id=m.to_user WHERE m.from_user=$1 OR m.to_user=$1 ORDER BY m.created_at ASC LIMIT 500`,[u.id]);res.json({ok:true,messages:r.rows})}catch(e){res.status(500).json({error:'Nie udało się pobrać wiadomości.'})}});
app.post('/api/messages',async(req,res)=>{try{const u=await authUser(req),to=Number(req.body?.toUserId),body=String(req.body?.body||'').trim().slice(0,500);if(!u)return res.status(401).json({error:'Zaloguj się.'});if(!Number.isInteger(to)||to===Number(u.id)||!body)return res.status(400).json({error:'Nieprawidłowa wiadomość.'});const f=await pool.query('SELECT id,username,avatar FROM users WHERE id=$1',[to]);if(!f.rows[0])return res.status(404).json({error:'Nie znaleziono gracza.'});const r=await pool.query(`INSERT INTO messages(from_user,to_user,body,kind) VALUES($1,$2,$3,'chat') RETURNING id,from_user,to_user,body,kind,room_code,created_at`,[u.id,to,body]),m={...r.rows[0],from_username:u.username,to_username:f.rows[0].username,from_avatar:u.avatar||'😀'};for(const sid of accountSockets.get(to)||[])io.to(sid).emit('privateMessage',m);res.json({ok:true,message:m})}catch(e){res.status(500).json({error:'Nie udało się wysłać wiadomości.'})}});
app.post('/api/friends/invite',async(req,res)=>{try{const u=await authUser(req),to=Number(req.body?.toUserId),code=String(req.body?.roomCode||'').trim().toUpperCase();if(!u)return res.status(401).json({error:'Zaloguj się.'});const rel=await pool.query('SELECT 1 FROM friends WHERE user_id=$1 AND friend_id=$2',[u.id,to]);if(!rel.rows.length)return res.status(403).json({error:'Możesz zapraszać tylko znajomych.'});const f=await pool.query('SELECT id,username,avatar FROM users WHERE id=$1',[to]);if(!f.rows[0])return res.status(404).json({error:'Nie znaleziono gracza.'});const r=await pool.query(`INSERT INTO messages(from_user,to_user,body,kind,room_code) VALUES($1,$2,$3,'invite',$4) RETURNING id,from_user,to_user,body,kind,room_code,created_at`,[u.id,to,'Zaproszenie do pokoju '+code,code]),m={...r.rows[0],from_username:u.username,to_username:f.rows[0].username,from_avatar:u.avatar||'😀'};for(const sid of accountSockets.get(to)||[])io.to(sid).emit('friendInvite',m);res.json({ok:true,message:m})}catch(e){res.status(500).json({error:'Nie udało się wysłać zaproszenia.'})}});
app.get('/api/shop',async(req,res)=>{try{const u=await authUser(req);if(!u)return res.status(401).json({error:'Zaloguj się.'});res.json({ok:true,coins:Number(u.coins||0),ownedDecks:u.owned_decks||['classic'],equippedDeck:u.equipped_deck||'classic',decks:PUBLIC_DECKS})}catch(e){res.status(500).json({error:'Nie udało się pobrać sklepu.'})}});
app.post('/api/shop/buy',async(req,res)=>{try{const u=await authUser(req),id=String(req.body?.deckId||''),d=DECKS[id];if(!u)return res.status(401).json({error:'Zaloguj się.'});if(!d)return res.status(404).json({error:'Nie znaleziono talii.'});let owned=Array.isArray(u.owned_decks)?u.owned_decks:['classic'];if(owned.includes(id))return res.json({ok:true,user:publicUser(u)});if(Number(u.coins)<d.price)return res.status(400).json({error:`Potrzebujesz ${d.price} coins.`});owned=[...owned,id];const r=await pool.query(`UPDATE users SET coins=coins-$1,owned_decks=$2::jsonb WHERE id=$3 RETURNING id,username,avatar,coins,owned_decks,equipped_deck`,[d.price,JSON.stringify(owned),u.id]);res.json({ok:true,user:publicUser(r.rows[0]),deck:d})}catch(e){res.status(500).json({error:'Nie udało się kupić talii.'})}});
app.post('/api/shop/equip',async(req,res)=>{try{const u=await authUser(req),id=String(req.body?.deckId||'');if(!u)return res.status(401).json({error:'Zaloguj się.'});if(!(Array.isArray(u.owned_decks)?u.owned_decks:['classic']).includes(id))return res.status(400).json({error:'Najpierw kup tę talię.'});const r=await pool.query(`UPDATE users SET equipped_deck=$1 WHERE id=$2 RETURNING id,username,avatar,coins,owned_decks,equipped_deck`,[id,u.id]);res.json({ok:true,user:publicUser(r.rows[0])})}catch(e){res.status(500).json({error:'Nie udało się wybrać talii.'})}});
app.get('/health',(_req,res)=>res.json({ok:true,database:!!process.env.DATABASE_URL}));
const value=r=>RANKS.indexOf(r);
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function sortHand(h){const o={'♣':0,'♦':1,'♥':2,'♠':3};h.sort((a,b)=>value(a.r)-value(b.r)||o[a.s]-o[b.s])}
function makeDeck(){return SUITS.flatMap(s=>RANKS.map(r=>({id:crypto.randomUUID(),key:`${s}|${r}`,s,r})))}
function newCode(){let c;do{c=crypto.randomBytes(3).toString('hex').toUpperCase()}while(rooms.has(c));return c}
function maxHandSize(n){return n===2?26:n===3?17:n===4?13:0}
function findPlayer(r,id){return r.players.find(x=>x.id===id)}
function findPlayerByToken(r,t){return t?r.players.find(x=>x.token===t)||null:null}
async function playerPhoto(id){if(!id)return null;try{const q=await pool.query('SELECT photo FROM profile_photos WHERE user_id=$1',[id]);return q.rows[0]?.photo||null}catch{return null}}
function publicRoom(r){return{code:r.code,phase:r.phase,round:r.round,maxRounds:r.maxRounds,handSize:r.handSize,trump:r.trump,currentPlayer:r.currentPlayer,currentDeclarer:r.currentDeclarer,currentTrumpChooser:r.currentTrumpChooser,stake:r.stake,maxPlayers:r.maxPlayers,readyPlayers:r.players.filter(p=>p.ready).map(p=>p.id),trick:r.trick.map(t=>({player:t.player,card:t.card})),roundHistory:r.roundHistory,players:r.players.map(p=>({id:p.id,name:p.name,avatar:p.avatar||'😀',avatarPhoto:p.avatarPhoto||null,score:p.score,decl:p.decl,won:p.won,roundPoints:p.roundPoints,connected:p.connected,ready:!!p.ready,accountUsername:p.accountUsername||null,accountId:p.accountId||null,equippedDeck:p.equippedDeck||'classic'}))}}
function stateFor(r,id){const p=findPlayer(r,id);return{room:publicRoom(r),myId:id,hand:p?.hand||[]}}
function send(r){for(const p of r.players)if(p.connected&&p.socketId)io.to(p.socketId).emit('state',stateFor(r,p.id))}
function attach(socket,r,p){p.socketId=socket.id;p.connected=true;socket.data.room=r.code;socket.data.playerId=p.id;socket.data.token=p.token;socket.join('room:'+r.code);if(p.accountId){let set=accountSockets.get(Number(p.accountId));if(!set){set=new Set();accountSockets.set(Number(p.accountId),set)}set.add(socket.id)}}
function detachAccount(socket,p){if(!p?.accountId)return;const set=accountSockets.get(Number(p.accountId));if(!set)return;set.delete(socket.id);if(!set.size)accountSockets.delete(Number(p.accountId))}
function next(r,id){const i=r.players.findIndex(x=>x.id===id);return r.players[(i+1)%r.players.length].id}
function trickWinner(r){const lead=r.trick[0].card.s;let best=0;for(let i=1;i<r.trick.length;i++){const a=r.trick[i].card,b=r.trick[best].card,at=a.s===r.trump,bt=b.s===r.trump;if(at&&!bt)best=i;else if(at===bt){const al=a.s===lead,bl=b.s===lead;if(al&&!bl)best=i;else if(al===bl&&value(a.r)>value(b.r))best=i}}return r.trick[best].player}
function startRound(r){if(r.round>r.maxRounds){finishGame(r);return}r.phase='trump';r.handSize=r.maxRounds-r.round+1;r.trick=[];r.currentPlayer=null;r.trump=null;r.currentTrumpChooser=r.players[(r.dealerIndex+1)%r.players.length].id;r.currentDeclarer=r.currentTrumpChooser;r.deck=shuffle(makeDeck());r.players.forEach(p=>{p.hand=[];p.decl=null;p.won=0;p.roundPoints=0;for(let i=0;i<r.handSize;i++)p.hand.push(r.deck.pop());sortHand(p.hand)});send(r)}
function chooseTrump(r,id,suit){if(r.phase!=='trump')return'Nie trwa wybór atutu.';if(r.currentTrumpChooser!==id)return'Teraz atut wybiera inny gracz.';if(!SUITS.includes(suit))return'Nieprawidłowy atut.';r.trump=suit;r.phase='declaration';r.currentDeclarer=id;send(r);return null}
function declarationSum(r){return r.players.reduce((s,p)=>s+(p.decl??0),0)}
function startPlay(r){r.phase='play';r.currentPlayer=r.players[(r.dealerIndex+1)%r.players.length].id;send(r)}
function declare(r,id,amount){const p=findPlayer(r,id);if(!p)return'Gracz nie istnieje.';if(r.phase!=='declaration')return'Nie trwa deklarowanie.';if(r.currentDeclarer!==id)return'Teraz deklaruje inny gracz.';const n=Number(amount);if(!Number.isInteger(n)||n<0||n>r.handSize)return'Nieprawidłowa deklaracja.';if(r.players.length>1&&declarationSum(r)-(p.decl??0)+n===r.handSize&&r.players.some(x=>x.id!==id&&x.decl===null))return'Nie można teraz domknąć sumy deklaracji.';p.decl=n;const i=r.players.findIndex(x=>x.id===id);r.currentDeclarer=r.players[(i+1)%r.players.length].id;if(r.players.every(x=>x.decl!==null))startPlay(r);else send(r);return null}
function play(r,id,card){if(r.lockedUntil&&Date.now()<r.lockedUntil)return'Poczekaj chwilę — poprzednia lewa jest jeszcze rozliczana.';const p=findPlayer(r,id);if(!p||r.phase!=='play'||r.currentPlayer!==id)return'Nie jest teraz Twoja kolej.';const wid=String(card?.id||''),wk=String(card?.key||''),ws=String(card?.s||''),wr=String(card?.r||'');let i=p.hand.findIndex(c=>String(c.id)===wid);if(i<0)i=p.hand.findIndex(c=>String(c.key)===wk);if(i<0)i=p.hand.findIndex(c=>c.s===ws&&c.r===wr);if(i<0)return'Nie mam takiej karty w tej ręce.';const played=p.hand[i],lead=r.trick[0]?.card.s;if(lead&&p.hand.some(c=>c.s===lead)&&played.s!==lead)return'Musisz dołożyć do koloru.';p.hand.splice(i,1);r.trick.push({player:id,card:played});if(r.trick.length<r.players.length){r.currentPlayer=next(r,id);send(r);return null}const win=trickWinner(r),wp=findPlayer(r,win);if(wp)wp.won++;r.currentPlayer=win;const completed=r.trick;r.lockedUntil=Date.now()+1300;send(r);setTimeout(()=>{if(!rooms.has(r.code)||r.trick!==completed)return;r.trick=[];r.lockedUntil=0;if(r.players.every(x=>x.hand.length===0))finishRound(r);else send(r)},1300);return null}
function finishRound(r){const results=r.players.map(p=>{const exact=p.won===p.decl;return{playerId:p.id,name:p.name,decl:p.decl,won:p.won,points:exact?10+p.won:0,exact}});results.forEach(x=>{const p=findPlayer(r,x.playerId);p.roundPoints=x.points;p.score+=x.points});r.roundHistory.push({round:r.round,results});r.phase='roundEnd';send(r);setTimeout(()=>{if(rooms.has(r.code)){r.round++;r.dealerIndex=(r.dealerIndex+1)%r.players.length;startRound(r)}},1400)}
async function finishGame(r){r.phase='finished';if(r.stake>0&&!r.potPaid){const ranked=[...r.players].sort((a,b)=>b.score-a.score),best=ranked[0]?.score||0,winners=ranked.filter(p=>p.score===best),share=Math.floor(r.pot/winners.length);for(const p of winners)if(p.accountId)await pool.query('UPDATE users SET coins=coins+$1 WHERE id=$2',[share,p.accountId]);r.potPaid=true}send(r)}
async function createPlayer(name,token,avatar){let u=null;try{u=await getUserFromToken(token)}catch{}const photo=await playerPhoto(u?.id);return{id:crypto.randomUUID(),token,name:cleanName(name||u?.username),avatar:cleanAvatar(avatar||u?.avatar),avatarPhoto:photo,accountId:u?.id||null,accountUsername:u?.username||null,equippedDeck:u?.equipped_deck||'classic',score:0,hand:[],decl:null,won:0,roundPoints:0,connected:false,socketId:null,ready:false}}
function stakeInfo(r,p){return{stake:r.stake,requiresReady:r.stake>0,ready:!!p.ready,canAfford:true,maxPlayers:r.maxPlayers}}
io.on('connection',socket=>{
 socket.on('resume',async({code,token}={})=>{const r=rooms.get(String(code||'').toUpperCase()),p=r&&findPlayerByToken(r,cleanToken(token));if(!r||!p)return;detachAccount(socket,p);attach(socket,r,p);const u=await getUserFromToken(token);if(u){p.accountId=u.id;p.accountUsername=u.username;p.avatar=u.avatar;p.equippedDeck=u.equipped_deck||'classic';p.avatarPhoto=await playerPhoto(u.id)}socket.emit('resumed',r.code);socket.emit('stakeInfo',stakeInfo(r,p));send(r)});
 socket.on('createRoom',async({name,token,avatar,stake,maxPlayers}={})=>{const code=newCode(),r={code,players:[],phase:'lobby',round:1,maxRounds:0,handSize:0,trump:null,currentPlayer:null,currentDeclarer:null,currentTrumpChooser:null,dealerIndex:0,deck:[],trick:[],roundHistory:[],lockedUntil:0,stake:Math.max(0,Math.floor(Number(stake)||0)),maxPlayers:Math.min(4,Math.max(2,Math.floor(Number(maxPlayers)||4))),pot:0,potPaid:false},p=await createPlayer(name,cleanToken(token)||crypto.randomUUID(),avatar);p.ready=r.stake===0;r.players.push(p);rooms.set(code,r);attach(socket,r,p);socket.emit('roomCreated',code);socket.emit('stakeInfo',stakeInfo(r,p));send(r)});
 socket.on('joinRoom',async({code,name,token,avatar}={})=>{const r=rooms.get(String(code||'').toUpperCase()),t=cleanToken(token)||crypto.randomUUID();if(!r)return socket.emit('errorMsg','Nie znaleziono pokoju.');const ex=findPlayerByToken(r,t);if(ex){attach(socket,r,ex);socket.emit('roomJoined',r.code);socket.emit('stakeInfo',stakeInfo(r,ex));send(r);return}if(r.phase!=='lobby')return socket.emit('errorMsg','Gra już się rozpoczęła.');if(r.players.length>=r.maxPlayers)return socket.emit('errorMsg','Pokój jest pełny.');const p=await createPlayer(name,t,avatar);p.ready=r.stake===0;r.players.push(p);attach(socket,r,p);socket.emit('roomJoined',r.code);socket.emit('stakeInfo',stakeInfo(r,p));send(r)});
 socket.on('setReady',async ready=>{const r=rooms.get(socket.data.room),p=r&&findPlayer(r,socket.data.playerId);if(!r||!p)return;const on=!!ready;if(on&&r.stake>0){const u=await getUserFromToken(p.token);if(!u||Number(u.coins)<r.stake){socket.emit('errorMsg','Nie masz wystarczająco monet na tę stawkę. Obejrzyj reklamę i odbierz 1000 coins.');socket.emit('stakeInfo',{...stakeInfo(r,p),canAfford:false});return}}p.ready=on;socket.emit('stakeInfo',stakeInfo(r,p));send(r)});
 socket.on('startGame',async()=>{const r=rooms.get(socket.data.room),p=r&&findPlayer(r,socket.data.playerId);if(!r||!p)return;if(r.players[0]?.id!==p.id)return socket.emit('errorMsg','Tylko twórca pokoju może rozpocząć.');if(r.players.length<2)return socket.emit('errorMsg','Potrzeba co najmniej 2 graczy.');if(r.players.length!==r.maxPlayers)return socket.emit('errorMsg',`Czekaj na wszystkich graczy (${r.players.length}/${r.maxPlayers}).`);if(r.stake>0){if(r.players.some(x=>!x.ready))return socket.emit('errorMsg','Każdy gracz musi zaakceptować stawkę.');const us=[];for(const x of r.players){const u=await getUserFromToken(x.token);if(!u||Number(u.coins)<r.stake)return socket.emit('errorMsg','Ktoś nie ma wystarczająco coinsów na tę stawkę.');us.push(u)}for(const u of us)await pool.query('UPDATE users SET coins=coins-$1 WHERE id=$2',[r.stake,u.id]);r.pot=r.stake*us.length}r.maxRounds=maxHandSize(r.players.length);r.round=1;r.dealerIndex=0;r.roundHistory=[];r.players.forEach(x=>x.score=0);startRound(r)});
 socket.on('chooseTrump',suit=>{const r=rooms.get(socket.data.room),e=r&&chooseTrump(r,socket.data.playerId,String(suit||''));if(e)socket.emit('errorMsg',e)});
 socket.on('declare',n=>{const r=rooms.get(socket.data.room),e=r&&declare(r,socket.data.playerId,n);if(e)socket.emit('errorMsg',e)});
 socket.on('play',card=>{const r=rooms.get(socket.data.room),e=r&&play(r,socket.data.playerId,card);if(e)socket.emit('errorMsg',e)});
 socket.on('requestState',()=>{const r=rooms.get(socket.data.room);if(r)send(r)});
 socket.on('leaveRoom',()=>{const r=rooms.get(socket.data.room),p=r&&findPlayer(r,socket.data.playerId);if(!r||!p)return;detachAccount(socket,p);r.players=r.players.filter(x=>x.id!==p.id);if(!r.players.length)rooms.delete(r.code);else send(r);socket.disconnect(true)});
 socket.on('disconnect',()=>{const r=rooms.get(socket.data.room),p=r&&findPlayer(r,socket.data.playerId);if(!p)return;if(p.socketId===socket.id){p.connected=false;p.socketId=null;detachAccount(socket,p)}send(r)});
});
const PORT=process.env.PORT||3000;initDatabase().then(()=>server.listen(PORT,()=>console.log('Planowanie server v10 listening on '+PORT))).catch(e=>{console.error('DATABASE START ERROR:',e);server.listen(PORT,()=>console.log('Planowanie server v10 listening on '+PORT+' (database error)'))});
